### PR TITLE
feat(input): replace cleaner icon #UIM-442

### PR DESCRIPTION
**Pull request by mikeozornin**
Replace cleaner icon #UIM-442

### CODE REVIEW

**Comment by PositiveJS** [comment]
Preview docs changes for cb4c163 at https://positive-js.github.io/mosaic-previews/pr461-cb4c163/

**Comment by Fost** [comment]
@mikeozornin pls update also **version**
https://github.com/positive-js/mosaic/blob/master/packages/mosaic/package.json#L27

This is the JSON file that is used when installing the package.

**Comment by mikeozornin** [comment]
@Fost Done

**Comment by PositiveJS** [comment]
Preview docs changes for af361dd at https://positive-js.github.io/mosaic-previews/pr461-af361dd/

**Pull request merged**
