### PR TITLE
feat(docs): adding checklist tree example  (#UIM-391)

### PR DESCRIPTION
**Pull request by Margar1ta**
Checklist tree example with child selection is added, selection is managed by SelectionModel.

### CODE REVIEW

**Comment by PositiveJS** [comment]
Preview docs changes for 28b807b at https://positive-js.github.io/mosaic-previews/pr429-28b807b/

**Comment by Fost** [comment]
https://positive-js.github.io/mosaic-previews/pr429-28b807b/tree/overview

**Comment by PositiveJS** [comment]
Preview docs changes for 41e7d4d at https://positive-js.github.io/mosaic-previews/pr429-41e7d4d/

**Comment by PositiveJS** [comment]
Preview docs changes for 61cba04 at https://positive-js.github.io/mosaic-previews/pr429-61cba04/

**Pull request merged**
