### PR TITLE
feat(docs): adding progress bar examples

### PR DESCRIPTION
**Pull request by Margar1ta**
Indeterminate progress bar and  basic progress bar examples are added

### CODE REVIEW

**Comment by Fost** [comment]
@Margar1ta модуль прогресса надо добавить ``mosaic-examples/mosaic-module.ts``
Для работы в Stackblitz

**Comment by Margar1ta** [comment]
Готово!

**Comment by PositiveJS** [comment]
Preview docs changes for ceee32d at https://positive-js.github.io/mosaic-previews/pr354-ceee32d/

**Comment by PositiveJS** [comment]
Preview docs changes for ceee32d at https://positive-js.github.io/mosaic-previews/pr354-ceee32d/

**Comment by PositiveJS** [comment]
Preview docs changes for 1cf3624 at https://positive-js.github.io/mosaic-previews/pr354-1cf3624/

**Pull request merged**
