### PR TITLE
(WIP): New palette, fonts and theme

### PR DESCRIPTION
**Pull request by mikeozornin**
Replace of: https://github.com/positive-js/mosaic/pull/748

### CODE REVIEW

**Comment by PositiveJS** [comment]
Preview docs changes for 31abd49 at https://positive-js.github.io/mosaic-previews/pr764-31abd49/

**Comment by PositiveJS** [comment]
Preview docs changes for 3b24f27 at https://positive-js.github.io/mosaic-previews/pr764-3b24f27/

**Comment by PositiveJS** [comment]
Preview docs changes for 2f92f30 at https://positive-js.github.io/mosaic-previews/pr764-2f92f30/

**Comment by agalaktionov** [comment]
@cm4fan в темной теме у поповера пропал дивайдер в хедере
image

**Comment by agalaktionov** [comment]
@bogdanhpk у warning тултипа более темная тень чем у белого и черного
image

**Comment by PositiveJS** [comment]
Preview docs changes for eed1a17 at https://positive-js.github.io/mosaic-previews/pr764-eed1a17/

**Comment by PositiveJS** [comment]
Preview docs changes for 2822ab2 at https://positive-js.github.io/mosaic-previews/pr764-2822ab2/

**Comment by PositiveJS** [comment]
Preview docs changes for ea7da76 at https://positive-js.github.io/mosaic-previews/pr764-ea7da76/

**Comment by PositiveJS** [comment]
Preview docs changes for 5f4e1b2 at https://positive-js.github.io/mosaic-previews/pr764-5f4e1b2/

**Comment by PositiveJS** [comment]
Preview docs changes for 19d3f4b at https://positive-js.github.io/mosaic-previews/pr764-19d3f4b/

**Comment by PositiveJS** [comment]
Preview docs changes for b2701b8 at https://positive-js.github.io/mosaic-previews/pr764-b2701b8/

**Comment by lskramarov** [comment]
при синке с релизом пришлось создать новую ветку и новый PR https://github.com/positive-js/mosaic/pull/799

**Pull request closed without merging**
