### PR TITLE
feat(docs): adding progress spinner examples (#UIM-273)

### PR DESCRIPTION
**Pull request by Margar1ta**
Добавлены два примера компонента  progress spinner с режимом determinate и indeterminate.

### CODE REVIEW

**Comment by PositiveJS** [comment]
Preview docs changes for 85a2146 at https://positive-js.github.io/mosaic-previews/pr372-85a2146/

**Comment by Fost** [comment]
@Margar1ta переведи пожалуйста на RU.
в остальном все хорошо.

**Comment by PositiveJS** [comment]
Preview docs changes for f502a0c at https://positive-js.github.io/mosaic-previews/pr372-f502a0c/

**Comment by Margar1ta** [comment]
Готово!

**Comment by PositiveJS** [comment]
Preview docs changes for 7fda2bf at https://positive-js.github.io/mosaic-previews/pr372-7fda2bf/

**Comment by PositiveJS** [comment]
Preview docs changes for 5711f1f at https://positive-js.github.io/mosaic-previews/pr372-5711f1f/

**Pull request merged**
