### PR TITLE
fix(tags): fixing tag's icons color

### PR DESCRIPTION
**Pull request by Margar1ta**
icon-color and hovered-icon-color are added to tags theming for icon styling,
state-disable_background and state-disable_color are added for styling tag's disabled state

### CODE REVIEW

**Comment by PositiveJS** [comment]
Preview docs changes for 5f64d88 at https://positive-js.github.io/mosaic-previews/pr424-5f64d88/

**Comment by lskramarov** [comment]
Task UIM-396 has a lot of sub tasks but there fixed only one ?

**Comment by Margar1ta** [comment]
Fixing all tasks will make PR rather big, it seems to be a good idea to separate them, plus https://github.com/positive-js/mosaic/pull/422 changes many files, that should be changed for UIM-396, so it should be merged before doing the rest of UIM-396

**Comment by PositiveJS** [comment]
Preview docs changes for 7a9b775 at https://positive-js.github.io/mosaic-previews/pr424-7a9b775/

**Comment by PositiveJS** [comment]
Preview docs changes for 1ea6feb at https://positive-js.github.io/mosaic-previews/pr424-1ea6feb/

**Comment by PositiveJS** [comment]
Preview docs changes for 5223bbe at https://positive-js.github.io/mosaic-previews/pr424-5223bbe/

**Pull request merged**
