### PR TITLE
feat(docs) : new tooltip docs

### PR DESCRIPTION
**Pull request by bogdanhpk**

### CODE REVIEW

**Comment by PositiveJS** [comment]
Preview docs changes for 4b8c291 at https://positive-js.github.io/mosaic-previews/pr798-4b8c291/

**Comment by agalaktionov** [comment]
https://github.com/positive-js/mosaic/pull/795#issuecomment-1022887040

**Comment by agalaktionov** [comment]
картинка в неверном размере, из-за чего превратилась в мыло
image

**Comment by PositiveJS** [comment]
Preview docs changes for 824b20e at https://positive-js.github.io/mosaic-previews/pr798-824b20e/

**Comment by PositiveJS** [comment]
Preview docs changes for cb39787 at https://positive-js.github.io/mosaic-previews/pr798-cb39787/

**Comment by PositiveJS** [comment]
Preview docs changes for cf91ec4 at https://positive-js.github.io/mosaic-previews/pr798-cf91ec4/

**Comment by PositiveJS** [comment]
Preview docs changes for b530699 at https://positive-js.github.io/mosaic-previews/pr798-b530699/

**Comment by PositiveJS** [comment]
Preview docs changes for 3a43bd8 at https://positive-js.github.io/mosaic-previews/pr798-3a43bd8/

**Comment by PositiveJS** [comment]
Preview docs changes for 4cfa768 at https://positive-js.github.io/mosaic-previews/pr798-4cfa768/

**Comment by PositiveJS** [comment]
Preview docs changes for 5877a66 at https://positive-js.github.io/mosaic-previews/pr798-5877a66/

**Comment by PositiveJS** [comment]
Preview docs changes for 2b67ae0 at https://positive-js.github.io/mosaic-previews/pr798-2b67ae0/

**Comment by PositiveJS** [comment]
Preview docs changes for a370709 at https://positive-js.github.io/mosaic-previews/pr798-a370709/

**Comment by PositiveJS** [comment]
Preview docs changes for 4b1c348 at https://positive-js.github.io/mosaic-previews/pr798-4b1c348/

**Comment by agalaktionov** [comment]
можно вливать в мастер

**Comment by PositiveJS** [comment]
Preview docs changes for a0e9893 at https://positive-js.github.io/mosaic-previews/pr798-a0e9893/

**Comment by lskramarov** [comment]
@agalaktionov добавил исправления от техрайтеров, посмотри еще раз, если все ок, поставь апрув.

**Review by agalaktionov — APPROVED** [review]

**Review by lskramarov — APPROVED** [review]

**Pull request merged**
