### PR TITLE
fix(chore): turns on strictTemplates (#UIM-794)

### PR DESCRIPTION
**Pull request by lskramarov**

### CODE REVIEW

**Comment by PositiveJS** [comment]
Preview docs changes for fbf27ae at https://positive-js.github.io/mosaic-previews/pr717-fbf27ae/

**Comment by PositiveJS** [comment]
Preview docs changes for ace8bb8 at https://positive-js.github.io/mosaic-previews/pr717-ace8bb8/

**Review by Fost — APPROVED** [review]

**Comment by PositiveJS** [comment]
Preview docs changes for 30779ee at https://positive-js.github.io/mosaic-previews/pr717-30779ee/

**Comment by PositiveJS** [comment]
Preview docs changes for a8c05b7 at https://positive-js.github.io/mosaic-previews/pr717-a8c05b7/

**Comment by PositiveJS** [comment]
Preview docs changes for bd8fc74 at https://positive-js.github.io/mosaic-previews/pr717-bd8fc74/

**Comment by PositiveJS** [comment]
Preview docs changes for 80e8a3d at https://positive-js.github.io/mosaic-previews/pr717-80e8a3d/

**Comment by PositiveJS** [comment]
Preview docs changes for 970c388 at https://positive-js.github.io/mosaic-previews/pr717-970c388/

**Pull request merged**
