### PR TITLE
feat: links colors for a the new color palette

### PR DESCRIPTION
**Pull request by mikeozornin**

### CODE REVIEW

**Comment by agalaktionov** [comment]
нужно ещё сбилдить токены командами 
`yarn run build:tokens:mosaic`
`yarn run build:tokens:docs`

**Comment by PositiveJS** [comment]
Preview docs changes for 948b44b at https://positive-js.github.io/mosaic-previews/pr750-948b44b/

**Comment by PositiveJS** [comment]
Preview docs changes for 8847685 at https://positive-js.github.io/mosaic-previews/pr750-8847685/

**Comment by PositiveJS** [comment]
Preview docs changes for 701bca7 at https://positive-js.github.io/mosaic-previews/pr750-701bca7/

**Pull request closed without merging**
